### PR TITLE
[#12] [#30] using shorter representation for protobuf map in output and sorted by key

### LINKED ISSUE #30: Map output is not sorted by key
**Describe the bug**
map output not sorted

**To Reproduce**
do not know. sometimes maps appear randomized

**Expected behavior**
maps consistently transmitted

### PR DESCRIPTION
**Pull request by taojunli**
add the feature for #12 
fixed #30

### CODE REVIEW

File: src/libCli/OutputFormatting.cpp [hunk 1]
```diff
@@ -306,6 +322,34 @@ std::string OutputFormatter::fieldToString(const grpc::protobuf::Message & f_mes
             result += generateHorizontalGuide(nameSize, maxFieldNameSize);
             result += " = " + colorize(ColorClass::MessageTypeName, "{}");
         }
+        if(f_fieldDescriptor->is_map())
+        {
+            //check if the type of the Key-Value simple or not
+            if(is_pair_simple(f_fieldDescriptor->message_type()))
+            {
+                std::map<std::string, std::string>kv_map;
```
Comment (rainerschoe) [inline src/libCli/OutputFormatting.cpp]: I like the idea of using map<string,string> but it will not always give correct results.
Example:
10 -> "10"
8 -> "8"

I think we still have to differentiate between different key-types here :(
However, it should be rather easy: As described [here](https://developers.google.com/protocol-buffers/docs/proto3#maps) bytes and floats are not allowed as map keys. This leaves Int, string. and we can probably promote all integers to int64_t/uint64_t

For value types we can stay with string.

File: src/libCli/OutputFormatting.cpp [hunk 2]
```diff
@@ -306,6 +322,34 @@ std::string OutputFormatter::fieldToString(const grpc::protobuf::Message & f_mes
...
+                for(int i=0; i< numberOfRepetitions; i++)
+                {
+                    std::pair<std::string, std::string> kv_pair;
```
Comment (rainerschoe) [inline src/libCli/OutputFormatting.cpp]: camelCase

File: src/libCli/OutputFormatting.cpp [hunk 3]
```diff
@@ -306,6 +322,34 @@ std::string OutputFormatter::fieldToString(const grpc::protobuf::Message & f_mes
...
+                        //using this method to get repeated message from field
+                        const google::protobuf::Message & subMessage = reflection->GetRepeatedMessage(f_message, f_fieldDescriptor, i);
+                        const google::protobuf::FieldDescriptor * k_fieldDescriptor = f_fieldDescriptor->message_type()->field(0);
+                        const google::protobuf::FieldDescriptor * v_fieldDescriptor = f_fieldDescriptor->message_type()->field(1);
+                        kv_pair.first = fieldValueToString(subMessage, k_fieldDescriptor, f_initPrefix, f_currentPrefix+f_initPrefix);
+                        kv_pair.second = fieldValueToString(subMessage, v_fieldDescriptor, f_initPrefix, f_currentPrefix+f_initPrefix);
+                    }
+                    kv_map.insert(kv_pair);
+                }
+
```
Comment (rainerschoe) [inline src/libCli/OutputFormatting.cpp]: We could still add the type information once at the start of the map:
f_fieldDescriptor->name()
And also the number of map entries.
See below for an example

File: src/libCli/OutputFormatting.cpp [hunk 4]
```diff
@@ -306,6 +322,34 @@ std::string OutputFormatter::fieldToString(const grpc::protobuf::Message & f_mes
             result += generateHorizontalGuide(nameSize, maxFieldNameSize);
             result += " = " + colorize(ColorClass::MessageTypeName, "{}");
         }
+        if(f_fieldDescriptor->is_map())
+        {
+            //check if the type of the Key-Value simple or not
+            if(is_pair_simple(f_fieldDescriptor->message_type()))
```
Comment (rainerschoe) [inline src/libCli/OutputFormatting.cpp]: nested "if"
please use "and" in first if

File: src/libCli/OutputFormatting.cpp [hunk 5]
```diff
@@ -306,6 +322,34 @@ std::string OutputFormatter::fieldToString(const grpc::protobuf::Message & f_mes
...
+                        kv_pair.second = fieldValueToString(subMessage, v_fieldDescriptor, f_initPrefix, f_currentPrefix+f_initPrefix);
+                    }
+                    kv_map.insert(kv_pair);
+                }
+
+                for(auto& p: kv_map)
+                {
+                    result += colorize(ColorClass::RepeatedFieldName, p.first) + " => " + colorize(ColorClass::StringValue, p.second) += "\n";
+                }
+                return result;
```
Comment (rainerschoe) [inline src/libCli/OutputFormatting.cpp]: maybe do not return here, but put rest of code in "else"

**Comment by rainerschoe** [comment]
tested it... looks good from a functional point of view
